### ISSUE TITLE
saving MIW files does fail

### ISSUE THREAD

**Issue by dirkessl** [MartinNohr/MagicImageWand#11]
I am using a 16GB SDHC card formatted as exfat and saving MIW files does not work, so macros can not be used. start.MIW saving also fails.

**Comment by MartinNohr** [comment]
I just checked in some code that should fix it. It works for me now, but it also failed on my 128GB card.

**Comment by MartinNohr** [comment]
Pretty sure this works now. I'll close it, but please reopen if you find any more problems.
