### ISSUE TITLE
Macro recording broken

### ISSUE THREAD

**Issue by MartinNohr** [MartinNohr/MagicImageWand#13]
"fails to create macro file".

**Comment by dirkessl** [comment]
haha, I just opened the same issue :-)

**Comment by MartinNohr** [comment]
We're good! Great minds think and test alike.
Anyway, I just fixed it. New code is there. I had the wrong open mode on the file. The new sdfat library works a little bit differently.
I just tried stringing some fire letters together, works great. You can put a little pause in between them to allow space between them. Use start pause command.
