### ISSUE TITLE
Long files are not playing

### ISSUE THREAD

**Issue by dirkessl** [MartinNohr/MagicImageWand#17]
Very long files like FlamesLong.bmp, Flamesverylong.bmp, MagicImageWandGrafiti.bmp are not playing through the LEDs. BMP Preview works fine

**Comment by MartinNohr** [comment]
Interesting. I'll figure it out.

**Comment by MartinNohr** [comment]
Found it. An old piece of code limiting names to 8.3 format. Fixed checked as soon as I verify it works.

**Comment by MartinNohr** [comment]
Code fixed and uploaded.
