### ISSUE TITLE
Lightbar: make hue,sat turn around at the end

### ISSUE THREAD

**Issue by dirkessl** [MartinNohr/MagicImageWand#18]
when turning the wheel for hue and sat it would be nice if the if the value goes back to 0 when reaching 255.

**Comment by MartinNohr** [comment]
Good idea. I'll change that.

**Comment by MartinNohr** [comment]
Leave brightness so it pins at 255 and 0? It might be kind of scary if the turn left from 0 and it goes to full brightness!

**Comment by MartinNohr** [comment]
Hue and Saturation now roll over, the brightness still pins at 0 and 255.

**Comment by MartinNohr** [comment]
I changed it so the rollover behavior can be changed in the option menu for the lightbar.

**Comment by MartinNohr** [comment]
Sadly, the code doesn't work. I'll fix it. I put it in without testing late at night!
