### ISSUE TITLE
Directory up should be on the top

### ISSUE THREAD

**Issue by dirkessl** [MartinNohr/MagicImageWand#22]
If you jump inside a directory with a lot of files by accident, going back can only be achieved by scrolling completely to the bottom. Workaround at the moment: turn on menu wrap

**Comment by MartinNohr** [comment]
Ok, I had it that way in the past, but I can't remember why I changed it. I'll make it first again.

**Comment by MartinNohr** [comment]
Any idea for a better symbol,  or is ^ ok?

**Comment by MartinNohr** [comment]
I changed the symbols to < and >. Seems to make more sense to me.
Back up folder is now sorted to the beginning of the list.

**Comment by dirkessl** [comment]
Great stuff! 

—
Dirk
www.essl.de | www.lenstagger.com | www.caffenol.org

**Comment by MartinNohr** [comment]
Thanks to your comments this thing is getting better and better. I'm very happy to have others involved in improving it. :-)
