### ISSUE TITLE
MIW Remote control esp pin input only, won't work

### ISSUE THREAD

**Issue by MartinNohr** [MartinNohr/MagicImageWand#26]
Pins 34-39 on esp32 are input only, they cannot be used for output control. I suggest pin 21, 22, 32, or 33. Although any of the other outputs could be used, there isn't any conflict since they aren't being used. But leaving the SD pins free means we could add an SD card if necessary in the future.
Please change the schematic.

**Comment by dirkessl** [comment]
Fixed
