### ISSUE TITLE
BMP Preview is upside down

### ISSUE THREAD

**Issue by dirkessl** [MartinNohr/MagicImageWand#27]
i guess because of the last change of the direction

**Comment by MartinNohr** [comment]
It is working fine for me. Remember that the images must be rotated CCW now. I also had to change the code, I presume you have loaded the latest source code. Which image is upside down?
While thinking about this, maybe the preview code should honor the upside down setting for the LED strip?

**Comment by dirkessl** [comment]
I was stupid, I used old files. Thanks for checking.
