### ISSUE TITLE
missing source files

### ISSUE THREAD

**Issue by dirkessl** [MartinNohr/MagicImageWand#40]
SdFatConfig.h and nvs_flash.h are missing from the source files.

**Comment by MartinNohr** [comment]
nvs_flash.h is part of the esp32 library. If it is missing try installing the latest board support. I do not want to add it to this github repository.
I don't understand why sdfatconfig.h would be missing. It has been required for a long time and has never been part of this github repository. It is part the sdfat library.

**Comment by dirkessl** [comment]
This was me being stupid... I tried compiling it with VsCode, which has no libraries installed. Works with the Arduino IDE.
