### ISSUE TITLE
Output 2 for the second LED stripe not work

### ISSUE THREAD

**Issue by ThomasKlee64** [MartinNohr/MagicImageWand#41]
Hello Martin,

i have a problem with the second LED Stripe, this one unfortunately does not work. I have selected in the menu under LED Strip Settings Total LED 288 and under LED wiring Mode 2. Unfortunately the second stripe is dead. Both LED strips are connected to the data pin input, is that correct?

What could I have done wrong here?

THX

Thomas

**Comment by ThomasKlee64** [comment]
Sorry, had forgotten to set the number of LED controllers to 2.

**Comment by MartinNohr** [comment]
Yep, that would certainly cause a problem! Glad you found it, it puzzled me.
