### ISSUE TITLE
No Function of the frame sensor

### ISSUE THREAD

**Issue by ThomasKlee64** [MartinNohr/MagicImageWand#46]
@Hello Martin,

I tried to test the function of the frame sensor input, unfortunately without success. In the program code the input pin is "22" but in the schematic it is "32". What is correct now. I have changed the 22 to 32 in the program, but there is no reaction when the input is connected to GND. Can you help me here?

**Comment by MartinNohr** [comment]
I haven't tested that in over a year. It did work at some point in the past. I'll look into and see what happened. Thanks for letting me know.

**Comment by MartinNohr** [comment]
The correct value for the GPIO is 32.
Did you set "Frame Counter:" in the menus to something other than 0? The 0 value means to ignore. It is the number of pulses required to advance one frame.

**Comment by MartinNohr** [comment]
I believe this works now so I'll close this issue. Just reopen it if it still doesn't work for you.
