### ISSUE TITLE
preview of 288 pixel bitmaps

### ISSUE THREAD

**Issue by MartinNohr** [MartinNohr/MagicImageWand#53]
Preview of 288 pixel bitmaps is broken. Scrolling causes very strange effects.

**Comment by DaveStu** [comment]
Indeed it does. Mine seems to duplicate about 20-25% of the image on the right hand side.
Not a deal breaker and certainly usable.

**Comment by MartinNohr** [comment]
It's a "little" math error! I'll fix it soon. ;-)

**Comment by DaveStu** [comment]
No rush, the main culprit was the dial interaction, that issue did get annoying

**Comment by MartinNohr** [comment]
I've almost got it working, just a little arithmetic problem when scaling down to 144 from 288. I should have it fixed in the next couple of days.

**Comment by MartinNohr** [comment]
Fixed. It works for me now! Let me know if any problems are found. I'll leave this issue open for a few days.

**Comment by MartinNohr** [comment]
Since it seems to be ok now, I'll close this thread.
