### ISSUE TITLE
StackArray.h missing

### ISSUE THREAD

**Issue by dirkessl** [MartinNohr/MagicImageWand#8]
when trying to compile on a Vanilla Arduino IDE Installation, StackArray.h is missing and is not installable through the Library Manager.

https://github.com/Ridhwanluthra/StackArray

needs to be installed manually to make it compile

**Comment by MartinNohr** [comment]
I just checked in some new code that doesn't need StackArray anymore. You can delete it. I don't remember why I even used it. I guess I forgot that C++ has stacks in std already.

**Comment by MartinNohr** [comment]
Working fine with std lib, stackarray no longer used.
